version: "3"
services:
  tcp-server:
    restart: always
    build: ./tcp-server
    command: python3 -u ./tcp-server/main.py
    ports:
      - "7777:7777"
    volumes:
      - .:/cleverest_machine
    links:
      - database
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    depends_on:
      - database
  test:
    build: ./tcp-server
    command: python3 -u ./tcp-server/tests.py
    volumes:
      - .:/cleverest_machine
    links:
      - database
      - tcp-server
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    depends_on:
      - database
      - tcp-server
  mongo-express:
    restart: always
    image: mongo-express
    environment:
        - ME_CONFIG_MONGODB_SERVER=database
        - ME_CONFIG_MONGODB_PORT=27017
        - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
        - ME_CONFIG_MONGODB_AUTH_DATABASE=buyqaw
        - ME_CONFIG_BASICAUTH_USERNAME=root
        - ME_CONFIG_BASICAUTH_PASSWORD=1234
    ports:
      - "8081:8081"
    links:
      - database
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    depends_on:
      - database
  database:
    restart: always
    image: mongo:3.0.2
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"